on: [push, pull_request]
name: build
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install golangci-lint
      run: |
        export GO111MODULE=on
        go get github.com/golangci/golangci-lint/cmd/golangci-lint
    - name: Run linters
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        golangci-lint run

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: build
      run: |
        export GO111MODULE=on
        GOOS=linux   GOARCH=amd64 go build -o bin/alertmanager-deadman-receiver-linux-amd64
    - name: upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: binaries
        path: bin/